### ISSUE TITLE
bills_urls command does not work

### ISSUE THREAD

**Issue by prsnca** [prsnca/openCommittee#3]
1. with no args given - the function fails and does not supply proper details:
   Traceback (most recent call last):
   File "manage.py", line 10, in <module>
     execute_from_command_line(sys.argv)
   File "/Users/Yaron/.virtualenvs/openCommittee/lib/python2.7/site-packages/django/core/management/**init**.py", line 399, in execute_from_command_line
     utility.execute()
   File "/Users/Yaron/.virtualenvs/openCommittee/lib/python2.7/site-packages/django/core/management/**init**.py", line 392, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/Users/Yaron/.virtualenvs/openCommittee/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
     self.execute(_args, *_options.**dict**)
   File "/Users/Yaron/.virtualenvs/openCommittee/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
     output = self.handle(_args, *_options)
   File "/Users/Yaron/projects/openCommittee/committeeVotes/management/commands/bills_urls.py", line 153, in handle
     commitee_bills = get_commitee_bills_since(options['date'])
   File "/Users/Yaron/projects/openCommittee/committeeVotes/management/commands/bills_urls.py", line 98, in get_commitee_bills_since
     if since_date <= bill_date <= datetime.date.today():
   TypeError: can't compare datetime.date to NoneType

It seems like 'since_date' is not initialized in the function - how do i give the 'options' argument the 'date' key?

**Comment by kobigro** [comment]
It seems that i have forgotten to put  a default value in the date argument.  I will add a default date of two weeks ago and that should fix It.
